const MAIN_THEME_COLOR = "#002884"
const MAIN_THEME_TEXT_COLOR = '#E2F0FB'

export default {
    VUE_APP_POSTS_PER_PAGE: 5,
    VUE_APP_MAIN_BG_CSS_COLOR: 'white',
    VUE_APP_MAIN_TEXT_CSS_COLOR: 'black',
    // Footer
    VUE_APP_FOOTER_BG_CSS_COLOR: MAIN_THEME_COLOR,
    VUE_APP_FOOTER_TEXT_CSS_COLOR: MAIN_THEME_TEXT_COLOR,
    // Navbar
    VUE_APP_NAVBAR_BG_CSS_COLOR: MAIN_THEME_COLOR,
    VUE_APP_NAVBAR_TEXT_CSS_COLOR: MAIN_THEME_TEXT_COLOR,

}
